services:
  # streamlit-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #
  #   ports:
  #     - "8501:8501"
  #
  #   env_file:
  #     - .env
  #
  #   restart: unless-stopped
  #
  #   volumes:
  #     - ./src:/app/src

  api:
    build:
      context: .
      dockerfile: apps/apis/Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - .env

    restart: unless-stopped

    volumes:
      - ./apps/apis/src:/app/apps/apis/src

    command: uvicorn apis.app:app --host 0.0.0.0 --port 8000 --reload